// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package model

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Box struct {
	ID        int32
	UserID    int32
	Name      string
	CreatedAt pgtype.Timestamp
	UpdatedAt pgtype.Timestamp
}

type Note struct {
	ID          int32
	UserID      int32
	Title       string
	Content     string
	KeepInInbox bool
	CreatedAt   pgtype.Timestamp
}

type NotesBox struct {
	NoteID    int32
	BoxID     int32
	CreatedAt pgtype.Timestamp
}

type User struct {
	ID        int32
	Email     string
	FullName  string
	IsActive  bool
	CreatedAt pgtype.Timestamp
	UpdatedAt pgtype.Timestamp
}
