services:
  postgres:
    image: postgres:17-alpine
    environment:
      POSTGRES_DB: zboxes_db
      POSTGRES_USER: zboxes_user
      POSTGRES_PASSWORD: zboxes_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U zboxes_user -d zboxes_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      PORT: 8080
      DATABASE_URL: "postgres://zboxes_user:zboxes_password@postgres:5432/zboxes_db?sslmode=disable"
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  postgres_data:
