name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the backend Docker image
      run: 
        docker build ./backend/ --file Dockerfile --tag zbox-backend:$(date +%s)
